4/11/2024


sudo nginx -t
sudo systemctl restart nginx

deploy website

docker build -f Dockerfile.dev -t llc-marketing .
docker run -p 4000:4000 -d llc-marketing:latest


root@ubuntu-s-1vcpu-1gb-nyc3-01:~/LearnLeetCode-Marketing/learn-leet-code/learn-leet-code# sudo certbot --nginx -d www.learnleetcode.com


* 3/1/2024

** 1h

14 : npm not fould lol. reistalled nvm.
27 : refactor contactform code
39 : I want to use this class extension because it appears to make it easier to use the already set styles
46 : hook error might be because of mismatching version of React and renderer (reactDOM)
53 : I suppose I dont know why this is an issue now? perhaps assume its becase of: npm version? something with webpack (is webpack even being used?). why are errs showing up in browser now.

** 1h

15: had AI refactor code to use lifecycle methods instead of hook.... lol. now it works. 
13:

** 1h


add to namecheap

ssh -p 21098 sunstgkd@68.65.120.143

** 1h

00 : fix form
1:12 - website officially deployed!





npm install, npm start
diff between npm and yarn?
justn dont use yarn anymore?

The error ERR_OSSL_EVP_UNSUPPORTED is related to the OpenSSL library, which is used by Node.js for cryptographic functions. This error can occur when a function tries to use an algorithm or key size that's not supported by your version of OpenSSL.
"The error message suggests that the issue is occurring when webpack is trying to create a hash. This is likely part of the build process for your project."

webpack trying to create a hash:
*versioning mismatch*

..props is the "spread operator"



***

WEBSITE TO DO
- change favicon
- change new employee onboarding to employee onboarding
- change title
